### ISSUE TITLE
AppVeyor GitHub App

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions.reactive#6]
### Description

I'm in the process of removing unused GitHub apps from the Fluent Assertions organization.
This repository is the only user of the AppVeyor app, but I don't see any usage of AppVeyor :thinking: 
Do you still use it?

**Comment by rose-a** [comment]
Nope, I don't use/need it, you can remove it if you want.

**Comment by jnyrup** [comment]
Thanks :+1: 
I've removed it :broom:
